### ISSUE TITLE
Games that work and StartApp.exe

### ISSUE THREAD

**Issue by ghost** [bloodelves88/CloudyNvCapture#5]
Hi,

I placed the DXGI.dll into the System32 folder after renamed the original. But it didn`t work.
So I went and do the same with SysWOW64 folder, but the same issue. 
Some questions:

- What're the games that worked? I tried Marfia 2 Demo and PainKiller Ressurection Demo.

- I've been coding with Nvidia Capture SDK 6.0 and it generates a StartApp.exe. Why doesn`t solution generate the same .exe.

**Comment by joelngwt** [comment]
1. I've only tried World of Warcraft and Unreal Engine 4 template games that I packaged myself.

2. This solution file doesn't generate StartApp.exe because I removed it. Streaming starts automatically when you launch your game.
