### ISSUE TITLE
 No shared memroy to open (no shared memory name in environment variable). pId =0000000000000000

### ISSUE THREAD

**Issue by ghost** [bloodelves88/CloudyNvCapture#6]
Hi,

I'm trying with World of Warcraft and I'm getting the **DXGI.shim** log:

https://github.com/bloodelves88/CloudyNvCapture/blob/aa5a108d7905021c6570aac13e7798e4ede7a4c7/samples/DirectxIFR/DXIFRShim/Common/AppParam.cpp#L35

`[DEBUG][16:56:38] No shared memroy to open (no shared memory name in environment variable). pId =0000000000000000`

**Comment by ngsp94** [comment]
Hi,

You can check out this thread: https://gridforums.nvidia.com/default/topic/1012/nvidia-grid-apis/dxifrshim-sample-does-not-work-/

Note that you need NVIDIA Grid to run shim. And the dll needs to be placed with the exe in the Binaries folder.

I get this sometimes too. Usually a restart of the game does the trick. Make sure you close all Unreal Engine instances before trying again.

Good luck!

**Comment by ghost** [comment]
Hi ngsp94,

Thanks for the tip. I already solved that. I coud get a NvIFR.h264 file.

So I have an other question about the -gpu and -audio paramters. Looking around the code I was trying to figure out the usage about that. For exemple, I'm using Nvidia Grid M60-8q as following the image

![nvidia grid board](https://user-images.githubusercontent.com/21323185/30568838-c7335496-9cad-11e7-819b-528d0563d23a.png)

Since it has 2 GPUs, then how many stream it capable to do?
